#!/bin/bash

git init
read -p "Presiona ENTER para continuar"
git add .
read -p "Presiona ENTER"
echo 'Escribe un comentario entre comillas (ejemplo: "Tu comentario"):'
read comentario
echo $comentario
git commit -m $comentario
git pull
echo --- Fin del script del GitHub ----
